# Generated by Django 5.1.2 on 2024-10-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('re_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'custom_user',
            },
        ),
    ]
