# Generated by Django 5.1.2 on 2024-10-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_customuser_re_password_alter_customuser_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
